; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
; set default environment to the emulator
default_envs = tdisplay
; common settings for all environments
[env]
platform = espressif32@7.0.1
board = lilygo-t-display
framework = espidf
build_flags = -ffast-math
monitor_speed = 115200
upload_speed = 921600
lib_deps = https://github.com/a159x36/TDisplayGraphics.git@^2.2.0

[env:tdisplay]

[env:tdisplay_s3]
board = lilygo-t-display-s3
build_flags = -ffast-math -DTTGO_S3 -DBOARD_HAS_PSRAM

[env:emulator]
platform_packages = ttgo-tdisplay-emulator@^5.4.0
upload_protocol = custom
upload_command = $PROJECT_PACKAGES_DIR/ttgo-tdisplay-emulator/emulate $SOURCE $BUILD_DIR $PROJECT_PACKAGES_DIR

[env:emulator_s3]
board = lilygo-t-display-s3
build_flags = -ffast-math -DTTGO_S3 -DBOARD_HAS_PSRAM
platform_packages = ttgo-tdisplay-emulator@^5.4.0
upload_protocol = custom
upload_command = $PROJECT_PACKAGES_DIR/ttgo-tdisplay-emulator/emulate $SOURCE s3